### ISSUE TITLE
AttributeError: 'SMILESLanguage' object has no attribute 'transform_encoding'

### ISSUE THREAD

**Issue by FarzanT** [PaccMann/paccmann_predictor#13]
Hello,
I am trying to run the model using data provided here: https://ibm.ent.box.com/v/paccmann-pytoda-data/folder/91164948454
But apparently the language model provided there is an older version that doesn't have the `transform_encoding` attribute.
How can I generate a new SMILESLanguage file? Or is there a valid version that I can download?

Here's the error stack:

```
INFO:PaccMannTest:Start data preprocessing...
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/smiles/smiles_language.py:177: FutureWarning: Loading languages will use a text files in the future
  "Loading languages will use a text files in the future", FutureWarning
WARNING:pytoda.smiles.smiles_language:NOTE: We found 545 smiles that failed to be transformed (excluding invalid smiles). Inspect the attribute `failed_transform_smiles`.
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:400: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:401: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/sklearn/utils/extmath.py:847: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/sklearn/utils/extmath.py:689: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/_csv_statistics.py:221: RuntimeWarning: All-NaN axis encountered
  maximum = np.nanmax(maximums, axis=0)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/_csv_statistics.py:222: RuntimeWarning: All-NaN axis encountered
  minimum = np.nanmin(minimums, axis=0)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/_csv_statistics.py:233: RuntimeWarning: invalid value encountered in true_divide
  / total_number_of_samples
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/_csv_statistics.py:246: RuntimeWarning: invalid value encountered in true_divide
  / total_number_of_samples
WARNING:pytoda.smiles.smiles_language:NOTE: We found 545 smiles that failed to be transformed (excluding invalid smiles). Inspect the attribute `failed_transform_smiles`.
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:400: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:401: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/sklearn/utils/extmath.py:847: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/sklearn/utils/extmath.py:689: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/_csv_statistics.py:221: RuntimeWarning: All-NaN axis encountered
  maximum = np.nanmax(maximums, axis=0)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/_csv_statistics.py:222: RuntimeWarning: All-NaN axis encountered
  minimum = np.nanmin(minimums, axis=0)
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/_csv_statistics.py:233: RuntimeWarning: invalid value encountered in true_divide
  / total_number_of_samples
/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/_csv_statistics.py:246: RuntimeWarning: invalid value encountered in true_divide
  / total_number_of_samples
INFO:PaccMannTest:Training dataset has 290677 samples, test set has 290677.
INFO:PaccMannTest:Device for data loader is cpu and for model is cpu
INFO:PaccMannTest:Number of parameters 8170369
INFO:PaccMannTest:Training about to start...

INFO:PaccMannTest:example_params.json
INFO:PaccMannTest:== Epoch [0/200] ==
Traceback (most recent call last):
  File "train_paccmann.py", line 348, in <module>
    args.training_name
  File "train_paccmann.py", line 239, in main
    for ind, (smiles, gep, y) in enumerate(train_loader):
  File "/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/drug_sensitivity_dataset.py", line 246, in __getitem__
    selected_sample[self.drug_name]
  File "/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/base_dataset.py", line 79, in get_item_from_key
    return self.__getitem__(self.get_index(key))
  File "/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/datasets/smiles_dataset.py", line 207, in __getitem__
    return self.smiles_language.smiles_to_token_indexes(self.dataset[index])
  File "/Users/ftaj/opt/anaconda3/envs/paccmann_predictor/lib/python3.7/site-packages/pytoda/smiles/smiles_language.py", line 594, in smiles_to_token_indexes
    return self.transform_encoding(
AttributeError: 'SMILESLanguage' object has no attribute 'transform_encoding'
```

**Comment by jannisborn** [comment]
HI @FarzanT, thanks for your interest in the work. 
Did you set up a conda environment using the instructions from the README? Your env is called `paccmann_predictor` but it seems your using a too recent version of `pytoda`, our data handling package (see [here](https://github.com/PaccMann/paccmann_datasets)). Can you run: 
``` sh
python3 -c "import pytoda; print(pytoda.__version__)"
```

This should give you a `0.0.3` as indicated in the `conda.yml`. Unfortunately, `pytoda` is not backwards compatible, so you cant have a recent version of pytoda (e..g `0.2.4`) when running that example. 

So the fix is to get pytoda version `0.0.3`. The command is this:

```sh
pip install git+https://github.com/PaccMann/paccmann_datasets@0.0.3
```
Hope this helps, pls let me know.

**NOTE**: If you want to work with the new pytoda version (which we generally recommend!), adapting the code in this repo should be straightforward, see an example in the `affinity` folder. We changed the format of the SMILES language from `.pkl` to `.json` and thus you'd need to convert your language using the script in pytoda or create the language from scratch (possible with the code "as is", it just takes longer at initialization).

**Comment by jannisborn** [comment]
Please reopen if applicable

**Comment by FarzanT** [comment]
Sorry for the delay.
Yes, your solution worked. Thank you!
