### ISSUE TITLE
Access to pre-trained BindingDB affinity model and required input files

### ISSUE THREAD

**Issue by ashlin-k** [PaccMann/paccmann_predictor#23]
I wasn't able to re-open #22 , so just creating a new issue with my response.

Thanks so much for the quick reply! I was specifically looking for the model that was trained on BindingDB, as the protein target I'm interested in is not a kinase, and BindingDB covers a wider range of protein target types. Would you happen to have this model?

Could you also confirm that the where to find the "smiles_language.json" and "protein_language.pkl" files required for predict_affinity.py? Not sure if I can just use the vocab.json file [here](https://ibm.ent.box.com/s/xtml12cbd9bwb97odxykbl5qzzh147ml/folder/165871116183) for the smiles language file. I haven't been able to find the protein language one.

I have also started trying to train my own model, however the input file formats are not clearly stated. If it is possible to provide clear descriptions of the input files to `train_affinity_regression.py`, that would be much appreciated!

**Comment by jannisborn** [comment]
Hi,

So the models I was pointed to **were** trained on BindingDB. Just on a subset containing human kinases. For a general model trained on all of BindingDB, see here: https://ibm.ent.box.com/v/paccmann-sarscov2-models

Go to "affinity" and you will find the model you're looking for. It includes the protein language and smiles language files.
For a detailed description of the model architecture and the training procedure please see the paper in MLST: https://iopscience.iop.org/article/10.1088/2632-2153/abe808/meta
See section 2.2.2 and 3.1.
Please apologize the brevity on the discussion of this model in that paper; the paper was focused on de novo molecular discovery and the affinity predictor was only a small part. That's why we have the two more detailed publications in JCIM on kinases where the model is also detailed better.

**Comment by ashlin-k** [comment]
Thanks for the links! I was able to successfully download the pretrained model, and I stored it in a directory called `paccmann_predictor/paccmann_saved_models`. When I tried to run `paccmann_predictor/examples/affinity/predict_affinity.py` as follow:

```
python examples/affinity/predict_affinity.py \
    paccmann_saved_models/affinity nyx_data/proteins.smi \
    <INPUT_SMILES.smi> \
    <OUTPUT_DIR> \
     -m bimodal_mca \
     -s paccmann_saved_models/affinity/smiles_serial/vocab.json \
     -p paccmann_saved_models/affinity/protein_language.pkl \
     -l <LABELS_FILEPATH.csv> \
     -c
```

I got a bunch of `KeyError`s due to a mismatch between expected `params` keys in the script, and the parameters provided in the model's `model_params.json`. I manually changed the model parameters in `model_params.json` to match the keys used in `BimodalMCA`:

```
smiles_padding_length - > ligand_padding_length
protein_padding_length -> receptor_padding_length
smiles_vocabulary_size -> ligand_vocabulary_size
protein_vocabulary_size -> receptor_vocabulary_size
```

When I got this working, I then encountered the following error:

```
Traceback (most recent call last):
  File "examples/affinity/predict_affinity.py", line 121, in main
    model.load(weights_path, map_location=device)
  File "/home/ashlin/installed/paccmann_predictor/paccmann_predictor/models/bimodal_mca.py", line 560, in load
    self.load_state_dict(weights)
  File "/home/ashlin/.conda/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BimodalMCA:
	Missing key(s) in state_dict: "ligand_embedding.weight", "receptor_embedding.weight", "ligand_convolutional_layers.ligand_convolutional_0.convolve.weight", "ligand_convolutional_layers.ligand_convolutional_0.convolve.bias", "ligand_convolutional_layers.ligand_convolutional_0.batch_norm.weight", "ligand_convolutional_layers.ligand_convolutional_0.batch_norm.bias", "ligand_convolutional_layers.ligand_convolutional_0.batch_norm.running_mean", "ligand_convolutional_layers.ligand_convolutional_0.batch_norm.running_var", "ligand_convolutional_layers.ligand_convolutional_1.convolve.weight", "ligand_convolutional_layers.ligand_convolutional_1.convolve.bias", "ligand_convolutional_layers.ligand_convolutional_1.batch_norm.weight", "ligand_convolutional_layers.ligand_convolutional_1.batch_norm.bias", "ligand_convolutional_layers.ligand_convolutional_1.batch_norm.running_mean", "ligand_convolutional_layers.ligand_convolutional_1.batch_norm.running_var", "ligand_convolutional_layers.ligand_convolutional_2.convolve.weight", "ligand_convolutional_layers.ligand_convolutional_2.convolve.bias", "ligand_convolutional_layers.ligand_convolutional_2.batch_norm.weight", "ligand_convolutional_layers.ligand_convolutional_2.batch_norm.bias", "ligand_convolutional_layers.ligand_convolutional_2.batch_norm.running_mean", "ligand_convolutional_layers.ligand_convolutional_2.batch_norm.running_var", "receptor_convolutional_layers.receptor_convolutional_0.convolve.weight", "receptor_convolutional_layers.receptor_convolutional_0.convolve.bias", "receptor_convolutional_layers.receptor_convolutional_0.batch_norm.weight", "receptor_convolutional_layers.receptor_convolutional_0.batch_norm.bias", "receptor_convolutional_layers.receptor_convolutional_0.batch_norm.running_mean", "receptor_convolutional_layers.receptor_convolutional_0.batch_norm.running_var", "receptor_convolutional_layers.receptor_convolutional_1.convolve.weight", "receptor_convolutional_layers.receptor_convolutional_1.convolve.bias", "receptor_convolutional_layers.receptor_convolutional_1.batch_norm.weight", "receptor_convolutional_layers.receptor_convolutional_1.batch_norm.bias", "receptor_convolutional_layers.receptor_convolutional_1.batch_norm.running_mean", "receptor_convolutional_layers.receptor_convolutional_1.batch_norm.running_var", "receptor_convolutional_layers.receptor_convolutional_2.convolve.weight", "receptor_convolutional_layers.receptor_convolutional_2.convolve.bias", "receptor_convolutional_layers.receptor_convolutional_2.batch_norm.weight", "receptor_convolutional_layers.receptor_convolutional_2.batch_norm.bias", "receptor_convolutional_layers.receptor_convolutional_2.batch_norm.running_mean", "receptor_convolutional_layers.receptor_convolutional_2.batch_norm.running_var", "context_attention_ligand_layers.context_attention_ligand_0.reference_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_0.reference_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_0.context_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_0.context_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_0.context_hidden_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_0.context_hidden_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_0.alpha_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_1.reference_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_1.reference_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_1.context_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_1.context_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_1.context_hidden_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_1.context_hidden_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_1.alpha_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_2.reference_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_2.reference_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_2.context_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_2.context_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_2.context_hidden_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_2.context_hidden_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_2.alpha_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_3.reference_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_3.reference_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_3.context_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_3.context_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_3.context_hidden_projection.projection.weight", "context_attention_ligand_layers.context_attention_ligand_3.context_hidden_projection.projection.bias", "context_attention_ligand_layers.context_attention_ligand_3.alpha_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_0.reference_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_0.reference_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_0.context_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_0.context_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_0.context_hidden_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_0.context_hidden_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_0.alpha_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_1.reference_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_1.reference_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_1.context_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_1.context_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_1.context_hidden_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_1.context_hidden_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_1.alpha_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_2.reference_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_2.reference_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_2.context_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_2.context_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_2.context_hidden_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_2.context_hidden_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_2.alpha_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_3.reference_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_3.reference_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_3.context_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_3.context_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_3.context_hidden_projection.projection.weight", "context_attention_receptor_layers.context_attention_receptor_3.context_hidden_projection.projection.bias", "context_attention_receptor_layers.context_attention_receptor_3.alpha_projection.projection.weight". 
	Unexpected key(s) in state_dict: "smiles_embedding.weight", "protein_embedding.weight", "smiles_convolutional_layers.smiles_convolutional_0.convolve.weight", "smiles_convolutional_layers.smiles_convolutional_0.convolve.bias", "smiles_convolutional_layers.smiles_convolutional_0.batch_norm.weight", "smiles_convolutional_layers.smiles_convolutional_0.batch_norm.bias", "smiles_convolutional_layers.smiles_convolutional_0.batch_norm.running_mean", "smiles_convolutional_layers.smiles_convolutional_0.batch_norm.running_var", "smiles_convolutional_layers.smiles_convolutional_0.batch_norm.num_batches_tracked", "smiles_convolutional_layers.smiles_convolutional_1.convolve.weight", "smiles_convolutional_layers.smiles_convolutional_1.convolve.bias", "smiles_convolutional_layers.smiles_convolutional_1.batch_norm.weight", "smiles_convolutional_layers.smiles_convolutional_1.batch_norm.bias", "smiles_convolutional_layers.smiles_convolutional_1.batch_norm.running_mean", "smiles_convolutional_layers.smiles_convolutional_1.batch_norm.running_var", "smiles_convolutional_layers.smiles_convolutional_1.batch_norm.num_batches_tracked", "smiles_convolutional_layers.smiles_convolutional_2.convolve.weight", "smiles_convolutional_layers.smiles_convolutional_2.convolve.bias", "smiles_convolutional_layers.smiles_convolutional_2.batch_norm.weight", "smiles_convolutional_layers.smiles_convolutional_2.batch_norm.bias", "smiles_convolutional_layers.smiles_convolutional_2.batch_norm.running_mean", "smiles_convolutional_layers.smiles_convolutional_2.batch_norm.running_var", "smiles_convolutional_layers.smiles_convolutional_2.batch_norm.num_batches_tracked", "protein_convolutional_layers.protein_convolutional_0.convolve.weight", "protein_convolutional_layers.protein_convolutional_0.convolve.bias", "protein_convolutional_layers.protein_convolutional_0.batch_norm.weight", "protein_convolutional_layers.protein_convolutional_0.batch_norm.bias", "protein_convolutional_layers.protein_convolutional_0.batch_norm.running_mean", "protein_convolutional_layers.protein_convolutional_0.batch_norm.running_var", "protein_convolutional_layers.protein_convolutional_0.batch_norm.num_batches_tracked", "protein_convolutional_layers.protein_convolutional_1.convolve.weight", "protein_convolutional_layers.protein_convolutional_1.convolve.bias", "protein_convolutional_layers.protein_convolutional_1.batch_norm.weight", "protein_convolutional_layers.protein_convolutional_1.batch_norm.bias", "protein_convolutional_layers.protein_convolutional_1.batch_norm.running_mean", "protein_convolutional_layers.protein_convolutional_1.batch_norm.running_var", "protein_convolutional_layers.protein_convolutional_1.batch_norm.num_batches_tracked", "protein_convolutional_layers.protein_convolutional_2.convolve.weight", "protein_convolutional_layers.protein_convolutional_2.convolve.bias", "protein_convolutional_layers.protein_convolutional_2.batch_norm.weight", "protein_convolutional_layers.protein_convolutional_2.batch_norm.bias", "protein_convolutional_layers.protein_convolutional_2.batch_norm.running_mean", "protein_convolutional_layers.protein_convolutional_2.batch_norm.running_var", "protein_convolutional_layers.protein_convolutional_2.batch_norm.num_batches_tracked", "context_attention_smiles_layers.context_attention_smiles_0.reference_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_0.reference_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_0.context_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_0.context_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_0.context_hidden_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_0.context_hidden_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_0.alpha_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_1.reference_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_1.reference_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_1.context_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_1.context_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_1.context_hidden_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_1.context_hidden_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_1.alpha_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_2.reference_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_2.reference_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_2.context_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_2.context_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_2.context_hidden_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_2.context_hidden_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_2.alpha_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_3.reference_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_3.reference_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_3.context_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_3.context_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_3.context_hidden_projection.projection.weight", "context_attention_smiles_layers.context_attention_smiles_3.context_hidden_projection.projection.bias", "context_attention_smiles_layers.context_attention_smiles_3.alpha_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_0.reference_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_0.reference_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_0.context_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_0.context_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_0.context_hidden_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_0.context_hidden_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_0.alpha_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_1.reference_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_1.reference_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_1.context_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_1.context_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_1.context_hidden_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_1.context_hidden_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_1.alpha_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_2.reference_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_2.reference_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_2.context_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_2.context_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_2.context_hidden_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_2.context_hidden_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_2.alpha_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_3.reference_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_3.reference_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_3.context_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_3.context_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_3.context_hidden_projection.projection.weight", "context_attention_protein_layers.context_attention_protein_3.context_hidden_projection.projection.bias", "context_attention_protein_layers.context_attention_protein_3.alpha_projection.projection.weight". 
	size mismatch for batch_norm.weight: copying a param with shape torch.Size([232]) from checkpoint, the shape in current model is torch.Size([259]).
	size mismatch for batch_norm.bias: copying a param with shape torch.Size([232]) from checkpoint, the shape in current model is torch.Size([259]).
	size mismatch for batch_norm.running_mean: copying a param with shape torch.Size([232]) from checkpoint, the shape in current model is torch.Size([259]).
	size mismatch for batch_norm.running_var: copying a param with shape torch.Size([232]) from checkpoint, the shape in current model is torch.Size([259]).
	size mismatch for dense_layers.dense_0.projection.weight: copying a param with shape torch.Size([20, 232]) from checkpoint, the shape in current model is torch.Size([20, 259]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/affinity/predict_affinity.py", line 230, in <module>
    args.confidence,
  File "examples/affinity/predict_affinity.py", line 123, in main
    raise ValueError(f'Error in model restoring from {weights_path}')
ValueError: Error in model restoring from paccmann_saved_models/affinity/weights/best_ROC-AUC_bimodal_mca.pt
```

I'm not sure but it looks like the model weight parameters may be misnamed, or can't be found in the saved model file `best_ROC-AUC_bimodal_mca.pt`.

**Comment by jannisborn** [comment]
Yes, this does not work because `predict_affinity` was added relatively recently to this repo and uses a more recent version of `paccmann_predictor` than this trained model. 

You could adapt the script to make it work but It's easier in another way: I just uploaded a new model to this Box folder: https://ibm.biz/active_site_data called `bindingdb_pretraining`. This model was pretrained on non-kinase targets from BindingDB as described in the JCIM paper: https://pubs.acs.org/doi/10.1021/acs.jcim.1c00889


You can use this instruction: https://github.com/PaccMann/paccmann_kinase_binding_residues#evaluating-the-bimca-model to run the code. The underlying model architecture is the same as the one in `predict_affinity` (the `BimodalMCA`).

**Comment by jannisborn** [comment]
Closing this issue. If you encounter problems, please feel free to open another in the https://github.com/PaccMann/paccmann_kinase_binding_residues repo

**Comment by ashlin-k** [comment]
Thank you, with some custom modifications to the script for my own input, I was able to get the above implementation working on my ligands!

**Comment by jannisborn** [comment]
Great to hear :)
