### ISSUE TITLE
Error in IC50 prediction due to dimension inconsistency

### ISSUE THREAD

**Issue by ghost** [PaccMann/paccmann_predictor#28]
I am glad to utilize your elaborate PaccMannV2 model. I accidentally found the error about dimension inconsistencies. 

  For example, I only left the first 322 IC50 values from splitted_data/gdsc_cell_line_ic50_test_fraction_0.1_id_997_seed_42.csv file. From 332 values, only 97 values have the corresponding cell-line and drug data, leaving the following error (**Error 1**). I encountered the same error when leaving the first 215 IC50 values, where only the 65 values were predictable. 

  I assume that the error occurs when the size of the last batch is 1, because setting the parameter drop_last=True in test dataset prevented this error. Conserving the batch size of drug embeddings (**Modification**) did not fixed the dimension error (**Erorr 2**).

# **Command**
```
python examples/IC50/test_paccmann.py \
    splitted_data/gdsc_example_322.csv \
    data/gene_expression/gdsc-rnaseq_gene-expression.csv \
    data/smiles/gdsc.smi \
    data/2128_genes.pkl \
    single_pytorch_model/smiles_language \
    single_pytorch_model/weights/best_mse_paccmann_v2.pt \
    results \
    single_pytorch_model/model_params.json
```

# **Error 1**
```
Traceback (most recent call last):
  File "examples/IC50/test_paccmann.py", line 217, in <module>
    args.smiles_language_filepath, args.model_filepath, args.predictions_filepath, args.params_filepath
  File "examples/IC50/test_paccmann.py", line 179, in main
    torch.squeeze(smiles.to(device)), gep.to(device), confidence = False
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "paccmann_predictor/models/paccmann_v2.py", line 250, in forward
    for ind in range(len(self.convolutional_layers))
  File "paccmann_predictor/models/paccmann_v2.py", line 250, in <listcomp>
    for ind in range(len(self.convolutional_layers))
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 1, 3, 128], but got 3-dimensional input of size [560, 1, 128] instead
```

# **Modification**
```
        for ind, (smiles, gep, y) in tqdm(enumerate(test_loader), total=len(test_loader)):
            y_hat, pred_dict = model(
                smiles.to(device), gep.to(device), confidence = False
                # torch.squeeze(smiles.to(device)), gep.to(device), confidence = False
            )
```

# **Error 2**
```
Traceback (most recent call last):
  File "examples/IC50/test_paccmann.py", line 218, in <module>
    args.smiles_language_filepath, args.model_filepath, args.predictions_filepath, args.params_filepath
  File "examples/IC50/test_paccmann.py", line 179, in main
    smiles.to(device), gep.to(device), confidence = False
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "paccmann_predictor/models/paccmann_v2.py", line 250, in forward
    for ind in range(len(self.convolutional_layers))
  File "paccmann_predictor/models/paccmann_v2.py", line 250, in <listcomp>
    for ind in range(len(self.convolutional_layers))
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "<Anaconda Directory>/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 560 elements not 64
```

[gdsc_example_215.csv](https://github.com/PaccMann/paccmann_predictor/files/14190907/gdsc_example_215.csv)
[gdsc_example_322.csv](https://github.com/PaccMann/paccmann_predictor/files/14190909/gdsc_example_322.csv)

**Comment by jannisborn** [comment]
Hi @Robust128,

Thanks for the interest in our work. Indeed, if the batch size is 1, the tensor gets squashed from 4D to 3D.
Based on your numbers I'm pretty sure the batch size is 32, because `65 % 32 = 1` but also `97 % 32 = 1`.

Be careful. Changing `batch_size` or setting `drop_last=True` is the most safe approach here. There are batch normalization layers in the network which cannot be meaningfully used with a batch of 1 sample, read [this discussion here](https://stackoverflow.com/questions/59648509/batch-normalization-when-batch-size-1)

The squashing you suggest as modification silences this unintended behavior. Our code raises intentionally an error here because passing a single sample is not meaningful. Hence, we cannot consider your suggestion for integration into the codebase.

Hope this helps!

**Comment by ghost** [comment]
Thank you for your quick answer.
I confirmed that changing the batch size in test_paccmann.py did not changed the prediction values.
Have a nice day!

[results_bs64.csv](https://github.com/PaccMann/paccmann_predictor/files/14191091/results_bs64.csv)
[results_bs128.csv](https://github.com/PaccMann/paccmann_predictor/files/14191092/results_bs128.csv)
